version: "3.9"

services:
  fastapi_app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres_db:5432/mydatabase
    volumes:
      - .:/app  # optional if you want live code reloading

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
